name: countrydialselector
description: "A Flutter widget for selecting countries and their international dialing codes."
version: 0.0.1
homepage: https://github.com/ridwan-101/countrydialselector

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/android.png
    - assets/ios.png
